version: '1'
services:
  ws:
    image: face-ws
    ports:
      - 7788:7788
    env_file:
      - .env

  flask:
    image: face-flask
    ports:
      - 5000:5000
    env_file:
      - .env

  redis:
    image: redis
    ports:
      - 6379:6379