version: '1'
services:
  redis:
    image: redis

  ws:
    image: face-ws
    depends_on:
      - redis
    env_file:
      - .env
    ports:
      - 7788:7788
    environment:
      - REDIS_IP=redis
      - LOG_SERVER_PREFIX=SERVER

  flask:
    image: face-flask
    depends_on:
      - redis
    env_file:
      - .env
    ports:
      - 5000:5000
    environment:
      - REDIS_IP=redis

networks:
  default:
    external:
      name: face