version: '1.1'
services:
  redis:
    image: redis

  ws:
    build:
      context: ./
      dockerfile: ./ws/Dockerfile
    depends_on:
      - redis
    env_file:
      - .env
    ports:
      - 7788:7788
    environment:
      - REDIS_IP=redis
      - LOG_SERVER_PREFIX=SERVER

  flask:
    build:
      context: ./
      dockerfile: ./flask/Dockerfile
    depends_on:
      - redis
    env_file:
      - .env
    ports:
      - 5000:5000
    environment:
      - REDIS_IP=redis

networks:
  face:
    name: face
    external: true